### ISSUE TITLE
Gnuradio-companion crash on open with missing glib key

### ISSUE THREAD

**Issue by petrushy** [conda-forge/gnuradio-feedstock#21]
Issue:
gnuradio-companion crashes on linux when selecting open in the file menu or ctrl+o.

The log gives:

(gnuradio-companion:14518): GLib-GIO-ERROR **: 20:13:58.060: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)

<br/>
Environment (<code>conda list</code>):

new environment installed with conda create -n gnuradio -c conda-forge gnuradio

<details>
The 
~/anaconda3/envs/gnuradio/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml 

has content
<key name='show-type-column' type='b'>
      <default>true</default>
      <summary>Show file types</summary>
      <description>
	Controls whether the file chooser shows a column with file types.
      </description>
    </key>

So somehow I have the feeling that this is not the accessed file. My system glib (2.56.4) does not have this key, so I guess somehow gnuradio is accessing there.

which gsettings 
/home/phy/anaconda3/envs/gnuradio/bin/gsettings

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : gnuradio
    active env location : /home/phy/anaconda3/envs/gnuradio
            shell level : 5
       user config file : /home/phy/.condarc
 populated config files : /home/phy/.condarc
                          /home/phy/anaconda3/envs/gnuradio/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/phy/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ryanvolz/linux-64
                          https://conda.anaconda.org/ryanvolz/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/phy/anaconda3/pkgs
                          /home/phy/.conda/pkgs
       envs directories : /home/phy/anaconda3/envs
                          /home/phy/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-59-generic linuxmint/19.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by petrushy** [comment]
Seems like it goes away  (open works)  if I downgrade glib to 3.24.14 (and gnuradio build 7)

  added / updated specs:
    - gtk3=3.24.14


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gtk3-3.24.14               |       h45fd312_2        19.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        19.5 MB

The following packages will be DOWNGRADED:

  alsa-lib                                 1.2.3-h516909a_0 --> 1.1.5-h516909a_1002
  gnuradio                           3.8.1.0-py37h2f024d0_9 --> 3.8.1.0-py37h4c8c553_7
  gnuradio-core                      3.8.1.0-py37head90f2_9 --> 3.8.1.0-py37h615a080_7
  gnuradio-grc                       3.8.1.0-py37h110162e_9 --> 3.8.1.0-py37h110162e_7
  gnuradio-qtgui                     3.8.1.0-py37he471202_9 --> 3.8.1.0-py37he471202_7
  gnuradio-uhd                       3.8.1.0-py37h132ed2f_9 --> 3.8.1.0-py37h110162e_7
  gnuradio-video-sdl                 3.8.1.0-py37h110162e_9 --> 3.8.1.0-py37h110162e_7
  gnuradio-zeromq                    3.8.1.0-py37h913d78c_9 --> 3.8.1.0-py37h913d78c_7
  gtk3                                   3.24.18-h45fd312_1 --> 3.24.14-h45fd312_2
  libcap                                    2.36-h516909a_0 --> 2.27-h516909a_0
  portaudio                               19.6.0-h1398938_3 --> 19.6.0-hf484d3e_2
  pulseaudio                                13.0-hd1b7508_1 --> 13.0-hd1b7508_0

**Comment by petrushy** [comment]
Somehow it is now working when creating new environment again third time. Sorry for the noise.

**Comment by ryanvolz** [comment]
It's possible that the `gtk3` post-link script didn't run, or failed to compile the glib schemas: https://github.com/conda-forge/gtk3-feedstock/blob/master/recipe/post-link.sh

This is something to keep an eye on, but I guess it's good that the issue magically fixed itself?

**Comment by petrushy** [comment]
That is indeed a very good form of magic. 

Thanks for all your work, really great development.
