### ISSUE TITLE
Gnuradio-companion not starting on windows 10

### ISSUE THREAD

**Issue by petrushy** [conda-forge/gnuradio-feedstock#33]
Hi

I'm having issues starting gnuradio-companion on windows (10). When starting, the program fails before setting up the GUI with an error dump as below. Seems to be somehow related to GTK (my guess), and perhaps not a GnuRadio issue, but not sure.

Tested w different python versions and a clean new conda environment. Did not reinstall all anaconda. Have only one windows machine, so potentielly could be some local stuff but looks like some library stuff.

Issue:
```
$ conda info
     active environment : gnuradio4
    active env location : C:\Users\XXXX\A3\envs\gnuradio4
            shell level : 2
       user config file : C:\Users\XXXX\.condarc
 populated config files : C:\Users\XXXX\.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.7.1.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\XXXX\A3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\XXXX\A3\pkgs
                          C:\Users\XXXX\.conda\pkgs
                          C:\Users\XXXX\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\XXXX\A3\envs
                          C:\Users\XXXX\.conda\envs
                          C:\Users\XXXX\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

```
** (process:2300): WARNING **: 10:22:17.830: Failed to load shared library 'gdk-3-vs15.dll' referenced by the typelib: 'gdk-3-vs15.dll': The specified procedure could not be found.
Traceback (most recent call last):
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\__init__.py", line 176, in require_foreign
    _gi.require_foreign(namespace, symbol)
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXX\A3\envs\gnuradio4\Library\bin\gnuradio-companion.exe\__main__.py", line 61, in check_gtk
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\__init__.py", line 178, in require_foreign
    raise ImportError(str(e))
ImportError: Couldn't find foreign struct converter for 'cairo.Context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\A3\envs\gnuradio4\Library\bin\gnuradio-companion.exe\__main__.py", line 100, in <module>
  File "C:\Users\XXXX\A3\envs\gnuradio4\Library\bin\gnuradio-companion.exe\__main__.py", line 67, in check_gtk
  File "C:\Users\XXXX\A3\envs\gnuradio4\Library\bin\gnuradio-companion.exe\__main__.py", line 42, in die
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\overrides\__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\overrides\Gdk.py", line 83, in <module>
    Color = override(Color)
  File "C:\Users\XXXX\A3\envs\gnuradio4\lib\site-packages\gi\overrides\__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

**Comment by ryanvolz** [comment]
Can you add the output of `conda list` so we know all of the exact packages involved?

You could try testing different versions of `gtk3` from conda-forge. If it works with some of them, that can help track down what's different and what would cause this.

**Comment by petrushy** [comment]
Hi,

I will do some experimenting with different versions of gtk and see if it gives some insight.

conda lsit:

# packages in environment at C:\Users\XXXX\A3\envs\gnuradio4:
#
# Name                    Version                   Build  Channel
adwaita-icon-theme        3.38.0               h5728ca3_1    conda-forge
atk-1.0                   2.36.0               he1ac64b_1    conda-forge
boost-cpp                 1.74.0               h54f0996_1    conda-forge
brotlipy                  0.7.0           py39ha3862ff_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hc79e3cf_1005    conda-forge
certifi                   2020.12.5        py39hcbf5309_0    conda-forge
cffi                      1.14.4           py39h0878f49_1    conda-forge
chardet                   3.0.4           py39h467e6f4_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
codec2                    0.9.2                h301d43c_1    conda-forge
cryptography              3.3.1            py39h0878f49_0    conda-forge
epoxy                     1.5.4                h8d14728_4    conda-forge
fftw                      3.3.8           nompi_hd3ad3c4_1114    conda-forge
freetype                  2.10.4               h546665d_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
gdk-pixbuf                2.42.2               hfe18499_1    conda-forge
gettext                   0.19.8.1          hfbb10ce_1004    conda-forge
glib                      2.66.3               h0e60522_0    conda-forge
gnuradio                  3.8.2.0          py39h66f841f_4    conda-forge
gnuradio-core             3.8.2.0          py39hd4f9262_4    conda-forge
gnuradio-grc              3.8.2.0          py39h856da1f_4    conda-forge
gnuradio-qtgui            3.8.2.0          py39hb757050_4    conda-forge
gnuradio-uhd              3.8.2.0          py39h6ff7f24_4    conda-forge
gnuradio-video-sdl        3.8.2.0          py39h856da1f_4    conda-forge
gnuradio-zeromq           3.8.2.0          py39h25b519f_4    conda-forge
gobject-introspection     1.66.1           py39h8f06b5a_1    conda-forge
gsl                       2.6                  hdfb1a43_1    conda-forge
gtk3                      3.24.24              he3dc4e2_0    conda-forge
hicolor-icon-theme        0.17                 h57928b3_2    conda-forge
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libblas                   3.8.0                    21_mkl    conda-forge
libcblas                  3.8.0                    21_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libglib                   2.66.3               h35efcdc_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.8.0                    21_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
librsvg                   2.50.2               hc15db13_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.1.0                hc10be44_6    conda-forge
libusb                    1.0.24               h0e60522_0    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
libxslt                   1.1.33               h579f668_1    conda-forge
log4cpp                   1.1.3             ha925a31_1002    conda-forge
lxml                      4.6.2            py39h4fd7cdf_0    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.1.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py39ha3862ff_2    conda-forge
menuinst                  1.4.16           py39hde42818_1    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
msys2-conda-epoch         20160418                      1
numpy                     1.19.4           py39h6635163_1    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
pango                     1.42.4               h8cb6782_4    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pip                       20.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
pycairo                   1.20.0           py39h8170971_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygobject                 3.38.0           py39hd9fc5f1_1    conda-forge
pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_6    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_6    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_6    conda-forge
pyqtchart                 5.12             py39h415ef7b_6    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_6    conda-forge
pysocks                   1.7.1            py39h467e6f4_2    conda-forge
python                    3.9.1           h7840368_1_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pywin32                   228              py39h4cdbadb_0    conda-forge
pyyaml                    5.3.1            py39ha3862ff_1    conda-forge
pyzmq                     20.0.0           py39h77b20cf_0    conda-forge
qt                        5.12.9               hb2cf2c5_0    conda-forge
qwt                       6.1.5                h265ddaf_0    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
sdl                       1.2.15               h21ff451_1    conda-forge
setuptools                49.6.0           py39h467e6f4_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
tzdata                    2020d                h516909a_0    conda-forge
uhd                       3.15.0.0         py39he0cccc2_5    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
volk                      2.3.0            py39h2da5c7c_3    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.36.1             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py39hde42818_1    conda-forge
wincertstore              0.2             py39hde42818_1005    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.2                ha925a31_4    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge

**Comment by petrushy** [comment]
Closing this as after a reinstall of conda, I ran into some issues and started to clean up settings folders all around. Cannot connect it to the error above but removing the .gnuradio folder in AppData\Roaming seems to have solved some issues. Likely the error was due to some settings file somewhere...
