### ISSUE TITLE
How to contribute to the gnuradio-feedstock

### ISSUE THREAD

**Issue by NicolasCaseau** [conda-forge/gnuradio-feedstock#50]
Hello, 

I'm trying to contribute to the conda-forge gnuradio packages but I don't know how. The modules I'm trying to submit on the conda-forge are called gr-ecss and gr-flaress. 

Could you please tell me how to do that ? I tried searching on the internet but I can't manage to do it. I apologize as I'm just a beginner on GitHub I hope I won't bother you too much.

Thank you 

Nicolas

**Comment by ryanvolz** [comment]
First you should write a recipe for each of those packages. You can refer to the documentation at https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html. You can also use an existing recipe ([gnuradio-satellites](https://github.com/conda-forge/gnuradio-satellites-feedstock) is a good one) as a template and change it to do what you need. I plan on building some tools to help with this, but it's a little ways off at this point. Once you've review the docs and played around with it a little bit, come back here if you have more questions.

Once you get that working, you can submit the recipes to conda-forge following their documentation at https://conda-forge.org/#contribute submit it to conda-forge. Feel free to add me as a maintainer and ping me on the pull request so I can help. I can even submit the recipes and include you so you can get a feel for the process if that would be easier.
