### ISSUE TITLE
Problem building an OOT module on a conda environnement 

### ISSUE THREAD

**Issue by NicolasCaseau** [conda-forge/gnuradio-feedstock#62]
Hi, 

I followed the tutorial to build an OOT module on gnuradio called "gr-howto". All the steps worked well except when I run the "ctest" command I get the following error : 

```
(gnuradio) [Nicolas@ppsle-asx-n build]$ ctest -V -R square 
UpdateCTestConfiguration  from :/home/Nicolas/gr-howto/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/Nicolas/gr-howto/build/DartConfiguration.tcl
Test project /home/Nicolas/gr-howto/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: qa_square_ff

1: Test command: /usr/bin/sh "/home/Nicolas/gr-howto/build/python/qa_square_ff_test.sh"
1: Test timeout computed to be: 10000000
1: Traceback (most recent call last):
1:   File "/home/Nicolas/gr-howto/python/qa_square_ff.py", line 13, in <module>
1:     from howto import square_ff
1: ImportError: cannot import name 'square_ff' from 'howto' (unknown location)
1: 
1: During handling of the above exception, another exception occurred:
1: 
1: Traceback (most recent call last):
1:   File "/home/Nicolas/gr-howto/python/qa_square_ff.py", line 19, in <module>
1:     from howto import square_ff
1: ImportError: cannot import name 'square_ff' from 'howto' (unknown location)
1/1 Test #1: qa_square_ff .....................***Failed    0.24 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.24 sec

The following tests FAILED:
	  1 - qa_square_ff (Failed)
Errors while running CTest
Output from these tests are in: /home/Nicolas/gr-howto/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
As you can see "square_ff" cannot be imported forw "howto". Wich is weird because when I ran the "cmake" and "make" commands, everything worked fine : 

```
(gnuradio) [Nicolas@ppsle-asx-n build]$ cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX ../
-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/Nicolas/anaconda3/envs/gnuradio/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/Nicolas/anaconda3/envs/gnuradio/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Found LOG4CPP: /home/Nicolas/anaconda3/envs/gnuradio/lib/liblog4cpp.so
-- Checking for module 'gmp'
--   Found gmp, version 6.2.1
-- Found GMP: /home/Nicolas/anaconda3/envs/gnuradio/lib/libgmpxx.so  
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Found MPIR: /home/Nicolas/anaconda3/envs/gnuradio/lib/libmpirxx.so  
-- Found MPLIB: /home/Nicolas/anaconda3/envs/gnuradio/lib/libgmpxx.so  
-- Found Boost: /home/Nicolas/anaconda3/envs/gnuradio/lib/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.74.0") found components: date_time program_options filesystem system regex thread 
-- Found Volk: Volk::volk  
-- User set python executable /home/Nicolas/anaconda3/envs/gnuradio/bin/python
-- Found PythonInterp: /home/Nicolas/anaconda3/envs/gnuradio/bin/python (found version "3.9.4") 
-- Found PythonLibs: /home/Nicolas/anaconda3/envs/gnuradio/lib/libpython3.9.so (found suitable exact version "3.9.4") 
-- Found PythonLibs: /home/Nicolas/anaconda3/envs/gnuradio/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/Nicolas/anaconda3/envs/gnuradio/include (found version "2.6.2" )
-- Checking for module 'thrift'
--   Found thrift, version 0.14.1
-- Python checking for Thrift - found
-- Found THRIFT: /home/Nicolas/anaconda3/envs/gnuradio/lib/libthrift.so  
-- Found Git: /usr/bin/git  
-- Found Doxygen: /home/Nicolas/anaconda3/envs/gnuradio/bin/doxygen (found version "1.9.1 (ab553a81f1725c385ca98109c269b0222389b72a*)") found components: doxygen missing components: dot
-- Using install prefix: /home/Nicolas/anaconda3/envs/gnuradio
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- PYTHON and GRC components are enabled
-- Python checking for pygccxml - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Nicolas/gr-howto/build


(gnuradio) [Nicolas@ppsle-asx-n build]$ make 
-- Build type not specified: defaulting to release.
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- User set python executable /home/Nicolas/anaconda3/envs/gnuradio/bin/python
-- Found pybind11: /home/Nicolas/anaconda3/envs/gnuradio/include (found version "2.6.2" )
-- Python checking for Thrift - found
-- Using install prefix: /home/Nicolas/anaconda3/envs/gnuradio
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- PYTHON and GRC components are enabled
-- Python checking for pygccxml - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Nicolas/gr-howto/build
Scanning dependencies of target gnuradio-howto
[ 12%] Building CXX object lib/CMakeFiles/gnuradio-howto.dir/square_ff_impl.cc.o
/home/Nicolas/gr-howto/lib/square_ff_impl.cc:14:78: note: #pragma message: set the following appropriately and remove this warning
   14 |     #pragma message("set the following appropriately and remove this warning")
      |                                                                              ^
/home/Nicolas/gr-howto/lib/square_ff_impl.cc:16:78: note: #pragma message: set the following appropriately and remove this warning
   16 |     #pragma message("set the following appropriately and remove this warning")
      |                                                                              ^
make[2]: AVERTISSEMENT : le fichier « /home/Nicolas/anaconda3/envs/gnuradio/lib/liblog4cpp.so » a une date de modification 8221017 s dans le futur
[ 25%] Linking CXX shared library libgnuradio-howto.so
make[2]: AVERTISSEMENT : décalage d'horloge détecté. La construction peut être incomplète.
[ 25%] Built target gnuradio-howto
Scanning dependencies of target doxygen_target
[ 37%] Generating documentation with doxygen
warning: Invalid value for 'FILTER_PATTERNS' tag at line 784, file /home/Nicolas/gr-howto/build/docs/doxygen/Doxyfile: Values in list '*.py="/home/Nicolas/gr-howto"/doc/doxygen/other/doxypy.py' are not properly space or comma separated
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 877 of file '/home/Nicolas/gr-howto/build/docs/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
error: Illegal format for option FILTER_PATTERNS, no equal sign ('=') specified for item '/doc/doxygen/other/doxypy.py'
[ 37%] Built target doxygen_target
Scanning dependencies of target extracted_docstrings
[ 50%] Scraping generated documentation for docstrings ...
[ 50%] Built target extracted_docstrings
Scanning dependencies of target howto_docstrings
[ 62%] Adding docstrings into howto pybind headers ...
output docstrings to /home/Nicolas/gr-howto/build/python/bindings/square_ff_pydoc.h
[ 62%] Built target howto_docstrings
Scanning dependencies of target howto_python
[ 75%] Building CXX object python/bindings/CMakeFiles/howto_python.dir/square_ff_python.cc.o
make[2]: AVERTISSEMENT : le fichier « /home/Nicolas/anaconda3/envs/gnuradio/include/python3.9/Python.h » a une date de modification 9117833 s dans le futur
[ 87%] Building CXX object python/bindings/CMakeFiles/howto_python.dir/python_bindings.cc.o
[100%] Linking CXX shared module howto_python.cpython-39-x86_64-linux-gnu.so
make[2]: AVERTISSEMENT : décalage d'horloge détecté. La construction peut être incomplète.
[100%] Built target howto_python


(gnuradio) [Nicolas@ppsle-asx-n build]$ sudo make install 
[sudo] Mot de passe de Nicolas : 
-- Build type not specified: defaulting to release.
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- User set python executable /home/Nicolas/anaconda3/envs/gnuradio/bin/python
-- Found pybind11: /home/Nicolas/anaconda3/envs/gnuradio/include (found version "2.6.2" )
-- Python checking for Thrift - found
-- Using install prefix: /home/Nicolas/anaconda3/envs/gnuradio
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- PYTHON and GRC components are enabled
-- Python checking for pygccxml - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Nicolas/gr-howto/build
make[2]: AVERTISSEMENT : le fichier « /home/Nicolas/anaconda3/envs/gnuradio/lib/liblog4cpp.so » a une date de modification 8220868 s dans le futur
[ 12%] Linking CXX shared library libgnuradio-howto.so
make[2]: AVERTISSEMENT : décalage d'horloge détecté. La construction peut être incomplète.
[ 25%] Built target gnuradio-howto
[ 37%] Built target doxygen_target
[ 50%] Scraping generated documentation for docstrings ...
[ 50%] Built target extracted_docstrings
[ 62%] Built target howto_docstrings
Scanning dependencies of target howto_python
make[2]: AVERTISSEMENT : le fichier « /home/Nicolas/anaconda3/envs/gnuradio/include/python3.9/Python.h » a une date de modification 9117694 s dans le futur
[ 75%] Building CXX object python/bindings/CMakeFiles/howto_python.dir/python_bindings.cc.o
[ 87%] Linking CXX shared module howto_python.cpython-39-x86_64-linux-gnu.so
make[2]: AVERTISSEMENT : décalage d'horloge détecté. La construction peut être incomplète.
[100%] Built target howto_python
```
Do you know hwo I could fix this issue ? Thank you and have a good day :)

**Comment by ryanvolz** [comment]
> (gnuradio) [Nicolas@ppsle-asx-n build]$ sudo make install

You don't need to use `sudo`, so `make install` is fine (it's installing to the conda environment, and your regular user has write permission for that). I don't think that's what's going wrong, but maybe it is.

In the last bit after your `sudo make install`, it builds everything again but I don't see it installing anything. I think there should be more logging that came after what you have shown, and that might help.

Are the errors any different or more informative if you run `python -c "from howto import square_ff"` directly in your activated terminal?

Finally, it's quite possible that the tutorial has a mistake in it. I've seen lots of similar postings to the mailing list and matrix chat that have nothing to do with conda. I might just give it a try myself to see what's actually broken.

**Comment by ryanvolz** [comment]
I tried out the `gr_modtool` tutorial, and though I came across one problem that needs to be fixed, I was able to get farther than you were. So for your issue, I do suspect that using `sudo` has messed up the module installation. Try `sudo make uninstall`, delete your build directory, and try again without the `sudo`.

If it's properly installed, you should have a `howto_python.cpython*.so` in `$CONDA_PREFIX/lib/python*/site-packages/howto`. If that exists and you get the same error, then there is something wrong with the compiled module that makes it impossible to import (e.g. could be permissions from using `sudo`).

My problems were two-fold:
1. `gr_modtool` didn't like the templates installed with the conda package, complaining of utf-8 parser errors. I've got a fix for this coming.
2. The test failed with `ImportError: generic_type: type "square_ff" referenced unknown base type "gr::block"`. I'm almost certain I've seen this recently on the mailing list, and it's related to differing pybind11 versions. I still have to make sure that's what it is and that I'm using the correct version.

**Comment by ryanvolz** [comment]
Ok, I've just actually updated to the latest `gnuradio` package and now see the same issue. I'll do more investigating.

**Comment by ryanvolz** [comment]
> Ok, I've just actually updated to the latest `gnuradio` package and now see the same issue. I'll do more investigating.

Actually I was wrong, it was not the same issue and it was due to a typo of my own in `qa_square_ff.py`. I now have the test passing.

The solution to (2) above (different pybind11 version) was either to upgrade to the latest `gnuradio` package, where I'd already made some changes in this area, or to install `gnuradio-build-deps` in the environment in order to ensure that `pybind11` was present and that it wouldn't pick up a system installation. I'll be pushing a PR to fix my issue (1) shortly.

As for your issue, again, I think `sudo` is the likely culprit. I'll update the GR conda wiki page with a note about how `sudo` should be avoided for conda installs.

**Comment by NicolasCaseau** [comment]
Hi,

Thank you for your answers, I will try again without the `sudo` and keep you posted.

Nicolas

**Comment by NicolasCaseau** [comment]
Ok so I tried using `make install` instead of `sudo make install ` and now I have errors relative to the administrative privileges so I don't think this is really the issue :  

```
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:46 (file):
  file cannot create directory:
  /home/Nicolas/anaconda3/envs/gnuradio/lib64/cmake/howto.  Maybe need
  administrative privileges.


make: *** [install] Erreur 1
```

In my first message I forgot to say that everything did install correctly and that the error occured after I entered `sudo make install `. I'm really sorry about that. 

Nicolas

**Comment by ryanvolz** [comment]
> Ok so I tried using `make install` instead of `sudo make install ` and now I have errors relative to the administrative privileges so I don't think this is really the issue :
> 
> ```
> -- Install configuration: "Release"
> CMake Error at cmake_install.cmake:46 (file):
>   file cannot create directory:
>   /home/Nicolas/anaconda3/envs/gnuradio/lib64/cmake/howto.  Maybe need
>   administrative privileges.
> 
> 
> make: *** [install] Erreur 1
> ```

You might need a fresh conda environment with errors like that: having created that directory as a super user, now your regular user doesn't have permission to modify it.

Regardless, it appears that it installed to a `lib64` directory, whereas what we require is `lib`. The installed gnuradio package should have provided the correct path to the OOT, but perhaps that only works with the latest one. If you still see `lib64` in your installed paths, you'll have to specify `-DLIB_SUFFIX=""` to cmake.

**Comment by NicolasCaseau** [comment]
Hi,
Sorry for the late answer I haven't had time to work on gnuradio for the past few weeks. 

So I tried building an OOT module called "signal_coding" and  everything worked fine and the module is now available on gnuradio companion. However when I try using the block I get an error : `AttributeError: module 'signal_coding' has no attribute 'coding'` 

Have you ever had this kind of issue and do you know how I could fix it ? I tried upgrading to the latest` gnuradio` package and installing the `gnuradio-build-deps` but I still get the error.

Thank you and have a good day :)

Nicolas

**Comment by ryanvolz** [comment]
Well it's not an `ImportError`, so it has found your module and it's good on that front. Evidently the GRC block files are being found as well. I think this points to something wrong in the Python module itself. Take a look at `signal_coding.py` and try to figure out what that message really means. Have you just not implemented whatever the `coding` attribute is supposed to be? Does it actually go by another name in the module?
